import type { Metadata } from "next"
import "./globals.css"
import Provider from "@/components/Provider"
import { ThemeProvider } from "@/components/ThemeContext"

export const metadata: Metadata = {
  title: "VibeChat",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <ThemeProvider>{children}</ThemeProvider>
        </Provider>
      </body>
    </html>
  )
}
